### ISSUE TITLE
inconsistent capitalization in condition type values and condition keys

### ISSUE THREAD

**Issue by HighlyTrainedNeuralNetwork** [Badaro/MTGOFormatData#100]
Some condition types are not capitalized in title case as the majority are. For instance "oneormoreInMainboard" over "OneOrMoreInMainboard". Additionally some condition keys are not capitalized "type" over "Type". I have a fix for this if I can get permissions to open a PR for it.

**Comment by Jiliac** [comment]
Hey, thanks for catching that :)

You don't need permission to open a PR. Github let's you fork a project, then push your change on any branch of the fork, and open a PR from this branch to the main repo.
