### ISSUE TITLE
[Pioneer] Gruul Prowess decks are sorted into "Mono-Red Aggro"

### ISSUE THREAD

**Issue by EAGrimaldi** [Badaro/MTGOFormatData#109]
They are admittedly pretty similar decks, but its probably worth separating them. Checking for non-red cards like Questing Druid or Stomping Ground seems like it would solve the issue, although I'm not very familiar with the project's "style guide" for defining archetypes.

**Comment by Badaro** [comment]
There's not strict guide on how/when to split decks, it's more about how we feel about expectations from the community combined with "how hard it ist to do". :)

Right now the most active maintainer is @Jiliac, so we let him give his $0.01 if he feels this separation is interesting or not. Another option is for you to also send a PR with a proposed split, and we can also discuss over that.

**Comment by Badaro** [comment]
@Aliquanto3 you're one of the main users of the data, so your input is also relevant here.

**Comment by Jiliac** [comment]
I think I chose to keep them together, let me have another look

**Comment by Aliquanto3** [comment]
I hardly follow the Pioneer metagame, so I can hardly say. I wouldn't even be able to tell what are the staples in that deck or what are its variations unless I'd actually look it into. Feel free to apply whatever you think is relevant.

**Comment by Jiliac** [comment]
The two points of I'm looking at when splitting archetypes is:
1. Do we have enough data on both versions to have significant results? (For ex we don't have enough data on mono-U spirits, so it's merged with azorius.)
2. Do these two versions have different game plan? (Implying different winrate and matchup spread.) For example jund and 5c creativity in modern play very differently.

I separated gruul and mono-R in the graph below. The answer to (1) is yes we have enough data. But I understand the 2 decks should have a very similar plan and matchup spread?

![image](https://github.com/Badaro/MTGOFormatData/assets/5956866/cfe574fd-ce1d-4c27-8971-a0137a060a87)
