### ISSUE TITLE
Modern Cleanup: Remove low-usage Archetypes

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGOFormatData#60]
To simplify maintenance I believe we should start triming low-usage archetypes. Since Modern is the oldest one and I initially was even trying to make it work even for Leagues, there's a lot of noise in the definitions that could be cleaned up.

I hacked the tool to extract some stats, this the usage count per archetype for:

* All managed metas (so since Dec/2019)
* Non-Leagues
* Non-Preliminaries
* Top 64 only

This is the output: https://pastebin.com/vd2X4Ajp

I intend to remove all archetypes below a specific threshold, maybe anything below 50 hits in this query? @Aliquanto3 do you have any opinions?

**Comment by Badaro** [comment]
If we go with the threshold I suggested above the following will be removed:

```
Usage count for Aggro/SagaAggro 0
Usage count for GenericTron/OathTron 2
Usage count for Titan/BreachTitan 4
Usage count for Phoenix/HollowPhoenix 0
Usage count for SoulSisters/NorinSisters 2
Usage count for Tokens 49
Usage count for AmuletLotus 48
Usage count for TrickeryCombo 47
Usage count for Weenies 44
Usage count for KinnanLegends 42
Usage count for OneShotProwess 35
Usage count for GeneralRokiric 26
Usage count for RotpriestCombo 26
Usage count for Stompy 25
Usage count for PyroAscension 24
Usage count for Superfriends 24
Usage count for BlackBurn 21
Usage count for Giants 20
Usage count for SerumPowderEldrazi 20
Usage count for ErayoPrison 18
Usage count for SongStorm 18
Usage count for ValakutField 15
Usage count for SelectiveOracle 14
Usage count for Skred 14
Usage count for Knightfall 13
Usage count for Eggs 11
Usage count for ZirdaCombo 11
Usage count for UrzaDiceFactory 9
Usage count for Lands 8
Usage count for MorophonSlivers 8
Usage count for SunforgerToolbox 7
Usage count for Zoo 7
Usage count for AuraReanimator 6
Usage count for Changelings 5
Usage count for GreenControl 5
Usage count for Grishoalbrand 5
Usage count for Insects 5
Usage count for ParadoxicalUrza 5
Usage count for ArtifactPrison 3
Usage count for Cheeri0s 3
Usage count for KethisCombo 3
Usage count for SeismicSwans 3
Usage count for SunAndMoon 2
Usage count for YawgmothSaga 2
Usage count for Allies 1
Usage count for Cats 1
Usage count for GoryoFootsteps 1
Usage count for Ninjas 1
Usage count for TunnelMoon 1
Usage count for EvershrikeCombo 0
Usage count for OboshMoon 0
Usage count for SacrificeTokens 0
Usage count for Werewolves 0
```

I don't see anything really significant, but I'll leave this up for comments for a day or two before going through with it.

**Comment by Aliquanto3** [comment]
I agree with the general idea.
Though at first glance the cut at 50 might be slightly too high, because
the decks I see in the 40s look somewhat relevant, at least for a past
period (for instance Trickery). Based on the results, I would be more
comfortable cutting around 36 copies (with OneShotProwess that should be
fine if aggregated with Prowess).
Can you easily run the same script since MH2 to see if most results of some
of those archetypes took place somewhat recently?

Le mer. 10 janv. 2024 à 22:39, Filipe Badaro ***@***.***> a
écrit :

**Comment by Badaro** [comment]
@Aliquanto3 maybe you just list the ones you think are relevant from the list I posted and we keep them? 

I think it's important to do a more aggressive trim here because with MH3 incoming we can expect a lot of of changes having cleaner definitions to start with will be very important, which is why I suggested the 50 threshold.

**Comment by Aliquanto3** [comment]
I guess Trickery Combo is the only one that I think is really relevant to keep... only if you want the parser to be relevant for the past years, since we are obviously never seeing that deck again.

**Comment by Badaro** [comment]
Keeping Trickery is a very low "cost" since it includes a banned card and that will keep it from creating conflicts in the future. 

And I agree it's relevant for historical reasons.

**Comment by Aliquanto3** [comment]
OK for me then. Keep Trickery and remove the other ones (maybe move them to a Modern - Old folder?).

**Comment by Badaro** [comment]
No need to keep a "Modern-Old" since we can always get them back from the Github history if necessary. :)
