### ISSUE TITLE
Modern Cleanup: Remove low-relevance variants

### ISSUE THREAD

**Issue by Badaro** [Badaro/MTGOFormatData#61]
Besides the large cleanup in #60, there's a few variants that I think can be safely removed and combined with the main archetype to simplify things:

From `Aggro`:

```
Usage count for Aggro/BreachValue 529
Usage count for Aggro/OboshRed 461
Usage count for Aggro/GenericMonkey 239
```

This leaves only Murktide, Burn and Prowess as variants, and may allow us to convert this into a Fallback which would be much cleaner than the current iteration of the rules.

From `Shadow`:

``` 
Usage count for Shadow/ShadowProwess 837
```

While this has significant numbers, I don't think most people care about the distinction.

From `Taxes`:

```
Usage count for Taxes/ThaliaStompy 816
Usage count for Taxes/EldraziTaxes 140
```

From `LivingEnd`:

```
Usage count for LivingEnd/JundLivingEnd 54
```

From `Affinity`:

```
Usage count for Affinity/UrzaAffinity 358
```

From `HeliodCombo`:

```
Usage count for HeliodCombo/HelioakCombo 61
```

From `Scapeshift`:

```
Usage count for Scapeshift/OmnathScapeshift 785
Usage count for Scapeshift/BlueScapeshift 389
Usage count for Scapeshift/BTLScapeshift 66
```

From `ThopterCombo`:

```
Usage count for ThopterCombo/ThopterUrza 837
```

Almost 100% of the results go into this variant, no need to keep it split.

From `SaheeliCombo`:

```
Usage count for SaheeliCombo/OmnathSaheeli 173
```

From `Zombies`:

```
Usage count for Zombies/Zombardment 42
```

From `Hollow One`:

```
Usage count for HollowOne/Hollowvine 75
```

From `SoulSisters`:

```
Usage count for SoulSisters/MartyrProc 38
```

While I understand that Martyr Proc is a different archetype, its prevalence seems too low to justify keeping it separately.

**Comment by Badaro** [comment]
@Aliquanto3 you're probably the best one to give feedback here. Do you see any variants that look relevant enough to keep in this list?

Remembering that these will still be identified, they'll simply fall into the "parent" archetype instead of the variant.

**Comment by Aliquanto3** [comment]
I would say a cut around 100 would be good here. There are still a few of them that seem relevant to split. Especially the Scapeshift decks that are widely different with or without blue, and still see regular play.
I think I would go as far as 300 if you really want to make some heavy cuts.

**Comment by Badaro** [comment]
@Aliquanto3  For these I'm not basing on # of results, more of my "gut feeling" of which ones are relevant or not. :D But going from your comment, maybe keep these:

```
Usage count for Scapeshift/OmnathScapeshift 785
Usage count for Scapeshift/BlueScapeshift 389
Usage count for Aggro/BreachValue 529
Usage count for Aggro/OboshRed 461
```

What do you think? Any others where the distinction from the "base" archetype looks particularly relevant?

**Comment by Aliquanto3** [comment]
Yeah, I just saw Breach value on MTGO this weekend again, it might be worth keeping around for now as well. And I guess Obosh aggro covers enough bases that it is worth maintaining for future random red decks. Having any way to specify red decks still seem relevant, otherwise I think the classification is way too generic (cf you dedicated issue ^^ ).
I am fine with all the other ones being classified as their parent otherwise, including some highly played ones, which make sense with their parents.

**Comment by Badaro** [comment]
Sounds good. I'll get this done soon.
